services:
  change-vol-ownership:
    image: alpine-deceasedcraft-persistent:latest
    user: root:root
    entrypoint: ""
    volumes:
      - G:\Minecraft\DeceasedCraft_Persistent:/tmp/DeceasedCraft/
    command: "chown -R dcmcsrv:dcmcsrv /tmp/DeceasedCraft"

  DeceasedCraft_Server_persistent:
    image: alpine-deceasedcraft-persistent:latest
    user: dcmcsrv:dcmcsrv
    ports:
      - 100.77.70.33:55565:25565
    volumes:
      - G:\Minecraft\DeceasedCraft_Persistent:/etc/DeceasedCraft/
    working_dir: "/etc/DeceasedCraft/"
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully